### ISSUE TITLE
Can't make the macro work (stupid)

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/perceptive#58]
Hi !

Trying to use the API to give the "recieve channel vision" to selected tokens, but I can't make it work, most likely because i'm dumb.

I got this (channel name is "test") : 

if (canvas.tokens.controlled.length > 0) {
    
    canvas.tokens.controlled.forEach(token => {
       
        token.document.update({
            'flags.perceptive.VisionChannelsFlag.test.Receives': true
        });
    });
    ui.notifications.info("Vision udpated !");
} else {
    ui.notifications.warn("Select a token !");
}

**Comment by Saibot393** [comment]
The problem seems to be, that you are using the channels name "test" instead of its internal id for th update.
I would recommend using the "Add Channels to Selected Objects" macro in the perceptive macro compendium (Examples->Vision Channels). The code for your specific use case would look like this:

```
let vChannelNames = ["test"];

let vTypes = ["Receives"]; //possible types: "Emits", "Receives", "Sight", "Movement"

let vChannelIDs = game.modules.get("perceptive").api.VisionChannelsUtils.VCIDsfromNames(vChannelNames);

let vObjects;

vObjects = canvas.tokens.controlled;

vObjects = vObjects.map(vObject => vObject.document);

game.modules.get("perceptive").api.VisionChannelsUtils.AddChannelstoObject(vObjects, vChannelIDs, vTypes);
```

**Comment by MastaGooz** [comment]
Ok, thanks a lot man !!
