### ISSUE TITLE
[Request] Check token lighting and vision when determining spotted

### ISSUE THREAD

**Issue by txm3278** [Saibot393/perceptive#6]
Mainly basing this off the dnd5e [rule](https://www.dndbeyond.com/sources/phb/adventuring#VisionandLight).

Also would love compatibility with the [vision5e](https://github.com/dev7355608/vision-5e) and the [limits](https://github.com/dev7355608/limits) module for checking vision

**Comment by Saibot393** [comment]
I will look into that for the next update. The second module should be relatively easy to integrate, for the first i will have to dig through the code a bit to see if i can do it.

**Comment by Saibot393** [comment]
One thing though, i can not access the D&D beyond link you included, are these the rules you were refering to https://www.dandwiki.com/wiki/5e_SRD:Vision_and_Light?

**Comment by txm3278** [comment]
Those rules you linked are the same as the ones I linked to on dndbeyond. By Vision I meant if the perceiving token has blindsight/darkvision/etc

**Comment by txm3278** [comment]
I also am having issues getting the spot feature to work at all. Is there any indication that a token has been spotted?

**Comment by Saibot393** [comment]
In the D&D 5e system there is currently no way for the GM to see if a token has been spotted by another token, only by logging in as a player that controls the spotting token.

**Comment by txm3278** [comment]
Ideally there would be an easy way for a dm to tell if a player token has been spotted at all (could be through an active effect on the hidden token being removed or any other way). I am basically trying to automate the hide action and this module seems to be leading possibly in that direction

**Comment by Saibot393** [comment]
Regarding automation, do you mean something like: You controll an NPC, roll the stealth skill and the token automatically gains the "Invisible" effect together with appropiate DC for spotting it? Something like this is deffinetly my end goal and the feature of automatically adding the stealth condition (whether its the Pf2e, DnD5e or DFreds convinient effects condition) will probably be part of the next bigger update

**Comment by txm3278** [comment]
Yes but not the invisible effect exactly because then things like see invisible could see it. Also things like a token standing in bright light with no cover should be a guarantied spot while one in dim would require the dc check

**Comment by Saibot393** [comment]
I will probably add something where the GM can specify which effects should be added when a stealth check is rolled (both on a world level and specifically for each token). Regarding the light level i will have to see how easy dim and bright light are do differentiate. If they are, i can probably add something like a bonus/mali system that can be set at world level for the spott dc dependent on the light level

**Comment by txm3278** [comment]
That all sounds great! The one other thing to check would be cover but that is a whole other can of worms that would probably require another module support so I understand not yet wanting to touch that

**Comment by Saibot393** [comment]
Yeah, cover is a bit hard to pin down in mathematical terms. It would however fit the "theme" of this module, so i will look into it though that may take a while

**Comment by txm3278** [comment]
There are many modules out there that already do cover very well, like [ATV](https://github.com/caewok/fvtt-token-visibility). It may be easier to just support one of these but I definitely understand wanting to build it yourself

**Comment by Saibot393** [comment]
I have just released v1.5.0 which should implement most of the things discussed here, including an easy way for the GM to check which tokens a player controlling a specific token can see (you may have to move the token to update the vision). 
The limits module seems to compatible by default from my testing.
For the vision 5e module i hvae only included some of the vision modes (dark vision und light amplification) since i was not quite sure yet how exactly the other modes should behave within the given rules (feel free to add suggestions for the other vision modes) but the general vision should now follow the expected behaviour of perceptive for hidden tokens.

**Comment by txm3278** [comment]
Thanks for all of this! That was extremely quick. I do have one question, for the "Illumination perception DC" is this the illumination of the hidden token or the one trying to spot them? Also is it possible to have this DC for passive checks but cause disadvantage for active checks instead?

**Comment by Saibot393** [comment]
For the Illumination perception DC modifier the light level at the position of the spotted/hidden token and the vision level(basic, dark vision) of the spotting token are relevant.
Applying disadvantage for spotting specific tokens is currently not possible since it is the rolling of the perception roll itself that triggers the check, so i don't have any influence on the result affter this. Though i might be able to add an option where a second "disadvantaged" check is rolled if an appropiate token/door is within the vision range.

**Comment by txm3278** [comment]
Also for the other senses, this [link](https://www.dandwiki.com/wiki/5e_SRD:Vision_and_Light) you sent has information for blindsight and truesight that would be helpful here, mainly that both should ignore darkness entirely when within range

**Comment by Saibot393** [comment]
I have added "blindsight", "truesight" and "devilssight" as "Darkvsion (Total)" Vision levels wtih v1.6.0

**Comment by Saibot393** [comment]
I thinks that should be all features mentioned in this issue, or did i miss/forget something?

**Comment by txm3278** [comment]
I think that is everything, thanks!
