### ISSUE TITLE
A5E System Compatibility

### ISSUE THREAD

**Issue by CyantoIogy** [Saibot393/perceptive#81]
The module loads, and it would appear the settings would allow you to see hidden objects, but nothing ever appears. I worked with the developers of the system, but we were unable to isolate any issues that were related to the system.

**Comment by Saibot393** [comment]
I will look into it, the module should normally be system agnostic. Do the perceptive settings show up in the token settings?

**Comment by Saibot393** [comment]
The problem was, that Advanced 5e outputs the rolls in a somewhat unconventional way, preventing perceptive from recognising them correctly. I have added explicit support for the system with v3.4.1. You may still need to set the passive perception formula per hand for everything to wortk (setting "Passive perception formula", value "@actor.system.skills.prc.passive"). I will leave this issue open for now in case i missed something

**Comment by CyantoIogy** [comment]
I had a chance to test it, and it's now working for spotting secret doors.

Thank you!
________________________________

**Comment by Saibot393** [comment]
good to hear
